import type {Metadata} from "next";
import {Nunito} from "next/font/google";
import "./globals.css";
import {Providers} from "@/app/(auth)/login/utils/providers";

const nunito = Nunito({
    variable: "--font-nunito",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Finrex",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body className={`${nunito.variable} antialiased`}>
        <Providers>
            {children}
        </Providers>
        </body>
        </html>
    );
}
